name: blog-build-push

on:
  push:
    branches: main

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Show CPU Model and Free Space
        run: |
          echo -e "Total CPU cores\t: $(nproc)"
          cat /proc/cpuinfo | grep 'model name'
          free -h
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ivyxjc/ivy-blog:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}